name: sonarqube

services:
  sonarqube:
    image: sonarqube:${SONAR_VERSION:-latest}
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "${SONAR_PORT:-127.0.0.1:9000}:9000"
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - ${SONAR_DIR:-./sonar-data}/data:/opt/sonarqube/data
      - ${SONAR_DIR:-./sonar-data}/logs:/opt/sonarqube/logs
      - ${SONAR_DIR:-./sonar-data}/extensions:/opt/sonarqube/extensions
    networks:
      - sonar-net

networks:
  sonar-net:
