name: sonarqube

services:
  sonarqube:
    image: sonarqube:10.7-community
    container_name: sonarqube
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL:-jdbc:postgresql://db:5432/sonarqube}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME:-sonar}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD:-sonarpassword}
    ports:
      - "${SONAR_PORT:-127.0.0.1:9000}:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
